# Numpy
Numpy is one of the most important foundational packages for Numerical computing in python<br>
Some of the important things in Numpy<br>
1. ndrray - multidimensional array for fast array-oriented and broadcasting operations
2. Fast mathematical opertions without for loops
3. reading/writing array data to the disk
4. memory-mapped files
5. Linear Algebra, random number generation

### Usage for Data Analysis operations
1. Fast vectorized multidimentioanl array operation for data cleanup, subsetting, filtering and other operations
2. Sorting, unique and set operations
3. Descriptive statistics, aggregating and summarizing data
4. Merging and Joining heterogenous datasets
5. conditional logic as array expressions
6. group-wise data manipulations

Numpy gives tremendous performance difference

In [1]:
import numpy as np
an_arr = np.arange(1000000)
a_list = list(range(1000000))

In [3]:
print(a_list)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [22]:
%time for _ in range(10): an_arr2 = an_arr * 2

Wall time: 78.1 ms


In [23]:
%time for _ in range(10): a_list2 = [x * 2 for x in a_list]

Wall time: 2.37 s


Numpy is 10 to 100 times faster than pure python based counterparts

### Numpy ndarray - Multidimensional Array Object
`ndarray` is one of the most important feature of Numpy<br>
`ndarray` is multidimensional container of homogeneous data<br>
All the elements are of same type<br>
each `ndarray` has `shape` and data type given by `dtype` of the array

In [24]:
import numpy as np
data = np.random.randn(2, 3)
data

array([[-0.83509111, -0.36760295,  0.27653662],
       [ 0.28021124,  0.05942262, -0.43267015]])

In [26]:
data+data

array([[-1.67018221, -0.73520589,  0.55307323],
       [ 0.56042247,  0.11884523, -0.86534029]])

above example each cell is added to each other

In [27]:
data.shape

(2, 3)

In [28]:
data.dtype

dtype('float64')

### Creating ndarrays
Easiest way to create array is to use `array` function. It accepts any sequence

In [29]:
dat1 = [6, 7.5, 8, 5, 8]
array1 = np.array(dat1)

In [30]:
array1

array([6. , 7.5, 8. , 5. , 8. ])

We can also create multidimensional array using nested sequences

In [31]:
dat2 = [[1, 2, 3, 4],[5, 6, 7, 8]]

In [32]:
array2 = np.array(dat2)
array2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

`ndim` and `shape` attributes give dimension and shape respectively

In [33]:
array2.ndim

2

In [34]:
array2.shape

(2, 4)

In [35]:
array1.dtype

dtype('float64')

In [36]:
array2.dtype

dtype('int32')

#### Other ways to create new arrays

`ones` - to create an array of 1s<br>
`zeros` - to create array of 0s<br>
`empty` - create array without initializing its values<br>
to create higher dimensional array pass the tuple as dimension of array<br>

#### Zero
`zero()` creates an array filled with zero values. arguement is an array or tulip with size of each dimension of the array

In [37]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [38]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

#### Ones
`ones()` - filled with one values.

In [39]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

#### Empty
`empty()` function create an array of specified shape. Arguement is an rray or tulip with lenght of each dimension of array<br>
Value created are random and empty array needs to be assigned before use<br>

In [40]:
np.empty((3, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

`np.empty` can give uninitialized garbage values with zeros

***
### Array Create Function
`array` - Convert input data (list, tuple, array, or other sequence type) to an ndarray either by inferring a dtype or explicitly specifying a dtype; copies the input data by default<br>
`asarray` - Convert input to ndarray, but do not copy if the input is already an ndarray
arange Like the built-in range but returns an ndarray instead of a list<br>
`ones`, `ones_like` - Produce an array of all 1s with the given shape and dtype; ones_like takes another array and produces a ones array of the same shape and dtype<br>
`zeros`,`zeros_like` - Like ones and ones_like but producing arrays of 0s instead<br>
`empty`,`empty_like` - Create new arrays by allocating new memory, but do not populate with any values like ones and zeros<br>
`full`,`full_like` - Produce an array of the given shape and dtype with all values set to the indicated “fill value” full_like takes another array and produces a filled array of the same shape and dtype<br>
`eye`, `identity` Create a square N × N identity matrix (1s on the diagonal and 0s elsewhere)

## Combining ndarray
New ndarrary can be created.<br>
`vstack()` and `hstack` are two popular methods<br>
`vstack()` - Vertical Stack<br>
`hstack()` - Horizontal Stack<br>
<br>

### Vertical Stack
Two or more array can be stacked vertically

In [41]:
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)
arr2 = np.array([[7,8,9],[10,11,12]])
print(arr2)
arr3 = np.vstack((arr1, arr2))
print(arr3)
print(arr3.shape)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


### Horizontal Stack
Two or more ndarray can be stacked horizontally

In [42]:
arr3 = np.hstack((arr1, arr2))
print(arr3)
print(arr3.shape)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
(2, 6)


### Concatenating ndarray
`concatenate()` take a sequence (tulip, list etc) and join them along input axis

In [43]:
arr3 = np.concatenate([arr1, arr2], axis=0)
print(arr3)
print(arr3.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [44]:
arr3 = np.concatenate([arr1, arr2], axis=1)
print(arr3)
print(arr3.shape)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
(2, 6)


### Splitting Array
divides the array into subarrays along a specified axis

In [45]:
a = np.arange(9)
print('first array')
print(a)
print('\n')
print('splitting the array in 3 equal size arrays')
b = np.split(a,3)
print(b)
print('\n')
print('splitting the array indicated first at 4, second 5- 7 remaining in 3rd')
c=np.split(a,[2,5,7])
print(c)
print('\n')

first array
[0 1 2 3 4 5 6 7 8]


splitting the array in 3 equal size arrays
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


splitting the array indicated first at 4, second 5- 7 remaining in 3rd
[array([0, 1]), array([2, 3, 4]), array([5, 6]), array([7, 8])]




### Data Types for ndarray
*data type* or `dtype` cobtains the information about the type of data

In [46]:
array1 = np.array([3, 4, 5], dtype = np.float64)

In [47]:
array2 = np.array([3, 4, 5], dtype = np.int32)

In [48]:
array1

array([3., 4., 5.])

In [49]:
array2

array([3, 4, 5])

In [50]:
array1.dtype

dtype('float64')

In [51]:
array2.dtype

dtype('int32')

The numerical data types are names same way<br>
a *type name* `int` or `float` followed by number of bits per element<br>
Standard doubleprecision floating-point value takes 8 bytes or 64 bits. So it is known as `float64` in Numpy<br>

### Numpy Data Types

`int8`, `uint8` - Signed and unsigned 8-bit (1 byte) integer types<br>
`int16`, `uint16` - Signed and unsigned 16-bit integer types<br>
`int32`, `uint32` - Signed and unsigned 32-bit integer types<br>
`int64`, `uint64` - Signed and unsigned 64-bit integer types<br>
`float16` - Half-precision floating point<br>
`float32` - Standard single-precision floating point; compatible with C float<br>
`float64` - Standard double-precision floating point; compatible with C double and Python float object<br>
`float128` - Extended-precision floating point<br>
`complex64`,
`complex128`,
`complex256` - Complex numbers represented by two 32, 64, or 128 floats, respectively<br>
`bool` - Boolean type storing True and False values<br>
`object` - Python object type; a value can be any Python object<br>
`string_` - Fixed-length ASCII string type (1 byte per character)<br>
`unicode_` U Fixed-length Unicode type (number of bytes platform specific)<br>

### Casting
You can convert or cast an array from one data type to another

In [52]:
arra1 = np.array([1, 2, 3, 4, 5])

In [53]:
arra1.dtype

dtype('int32')

In [54]:
arra1.astype(np.float64)

array([1., 2., 3., 4., 5.])

If the float is casted into int, the decimal is truncated

In [55]:
arra1 = np.array([1.5, 2.9, 3.1, 4.0])
arra1.astype(np.int32)

array([1, 2, 3, 4])

You can convert a string representing numbers into number using `astype`

In [56]:
arra1 = np.array(['1.25', '2.45', '3.55'], dtype=np.string_)

In [57]:
arra1.astype(np.float64)

array([1.25, 2.45, 3.55])

### Arithmetic with Numpy Array
Numpy support the batch operations on data without `for` loops. This is call as *vectorization*

In [58]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
arr+arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [60]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [61]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [62]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [63]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

#### Comparision of array

In [69]:
arr2 = np.array([[3,4,5],[6,7,8]])
arr2

array([[3, 4, 5],
       [6, 7, 8]])

In [67]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
arr2>arr1

array([[ True,  True,  True],
       [False,  True,  True]])

### Array Indexing
You can access data in Numpy using Indexing

#### One Dimensional Indexing
You can access One Dimensional Indexing using bracket operator [] by specifying the zero offset value

In [70]:
arr = np.array([10, 20, 30, 40, 50])

In [71]:
arr[0]

10

In [72]:
arr[4]

50

If you specify too large value of index, you will get IndexError

In [73]:
arr[6]

IndexError: index 6 is out of bounds for axis 0 with size 5

***
You can use negative index to get value offset from end 

In [74]:
arr[-1]

50

In [75]:
arr[-3]

30

### Two Dimensional Index
use comma to separate the index of each dimension

In [77]:
arr2d=np.array([[10, 20, 30],[40, 50, 60]])
arr2d

array([[10, 20, 30],
       [40, 50, 60]])

In [78]:
print(arr2d[0,0])
print(arr2d[1,2])
print(arr2d[1,0])

10
60
40


If we are interested in all the items in a row, we can leave the second dimension index empty

In [79]:
arr2d[1,]

array([40, 50, 60])

## Array Slicing
slicing is specified using a colon operator `:` with *from* and *to* arguements<br>
`data[from:to]`

### One Dimensional Slicing
You can index all data using slice : with no index

In [80]:
arr[:]

array([10, 20, 30, 40, 50])

The elements in array can be sliced by inputting the slice `from` and `to` index. Slice starts from `from` index and stop one index before `to`. For example:[3,5] will have index 3 and 4 but not 5

In [81]:
arr[2:5]

array([30, 40, 50])

In [82]:
arr[0:1]

array([10])

#### Negative Index
Negative index takes the slice to the end of the dimension and count from end. `-2` index in `from` means, counting starts two from end and `to` means number of steps in forward direction. If we leave `to` blank, it would go till end

In [83]:
arr[-2:]

array([40, 50])

In [52]:
arr[-3:-1]

array([30, 40])

#### Assign a value to a slice
A scalar value can be assigned to a slice also. It broadcasts to the whole slice. 

In [84]:
arr1 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [85]:
arr1[3:6]

array([40, 50, 60])

In [86]:
arr1[3:6] = 100

In [56]:
arr1

array([ 10,  20,  30, 100, 100, 100,  70,  80,  90])

<div class="alert alert-block alert-info">
<b>Tip:</b> Array slices create a view on the array. The array is not copied. Any change in any element of array slice will change the element in original array
</div>

In [87]:
slice_arr = arr1[3:6]

In [58]:
slice_arr

array([100, 100, 100])

In [88]:
slice_arr[1] = 110

In [89]:
arr1

array([ 10,  20,  30, 100, 110, 100,  70,  80,  90])

In [61]:
slice_arr[:] = 120

In [62]:
arr1

array([ 10,  20,  30, 120, 120, 120,  70,  80,  90])

#### Step Parameter
Python slice object can be created by using start, stop and step parameters<br>
arr1[1:7:2]<br>
means slicing starts from 1 upto 7 (7 not included) with step of 2

In [66]:
arr1[1:7:2]

array([ 20, 120, 120])

### Two Dimensional Slicing
In two dimensional slicing, the elements at index are not scalars but they are one dimensional array

In [91]:
arr2d = np.array([[1, 2, 3],[4,5,6], [7, 8, 9]])

In [92]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [93]:
arr2d[1:] #First row onwards

array([[4, 5, 6],
       [7, 8, 9]])

In [94]:
arr2d[:1] #Upto first row

array([[1, 2, 3]])

In [95]:
arr2d[0,2] #For individual element

3

In [96]:
arr2d[:,1] #all rows column at  index 1

array([2, 5, 8])

In [72]:
arr2d[:,0:1] #all rows column at index 0

array([[1],
       [4],
       [7]])

In [78]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [79]:
print(arr2d[2])
print(arr2d[2].shape)

[7 8 9]
(3,)


In [80]:
print(arr2d[2,:])
print(arr2d[2,:].shape)

[7 8 9]
(3,)


In [81]:
print(arr2d[2:,:])      #Using : you can access higher dimensional arrays
print(arr2d[2:,:].shape)

[[7 8 9]]
(1, 3)


### Multidimensional Array

In [98]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [99]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [102]:
arr3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [106]:
arr3d[1,0, 1]

8

In [77]:
arr3d[:,:,0:1]

array([[[ 1],
        [ 4]],

       [[ 7],
        [10]]])

### Boolean Index

In [110]:
names = np.array(['sam','bob','nick','sally','tom','sam','tina'])
data = np.random.randn(7,4)
names

array(['sam', 'bob', 'nick', 'sally', 'tom', 'sam', 'tina'], dtype='<U5')

In [111]:
data

array([[ 0.03012037,  0.89247625, -0.16728324,  0.91293339],
       [-0.33013837,  1.03685685, -0.76444672, -0.72360207],
       [-0.02855973, -0.47891146, -0.26946031,  1.34331514],
       [-0.11665027,  0.08346127, -0.16274915,  0.79340071],
       [ 1.65818193,  0.61391393,  0.73376547, -0.45726756],
       [ 1.27638825,  0.06818587, -0.44883013, -0.24630028],
       [-0.4951951 , -0.69942292,  0.39548398,  1.26096258]])

In [112]:
names == 'sam' # comparasion with array are also vectorized. This yields boolean array

array([ True, False, False, False, False,  True, False])

In [113]:
data[names=='sam'] # returns the rows where the boolean array has value True

array([[ 0.03012037,  0.89247625, -0.16728324,  0.91293339],
       [ 1.27638825,  0.06818587, -0.44883013, -0.24630028]])

boolean array should have same length as axis it is indexing. You can mix and match boolean rray with slicing

In [114]:
data[names == 'sam', 2:]

array([[-0.16728324,  0.91293339],
       [-0.44883013, -0.24630028]])

In [117]:
data[names == 'sam', 3]

array([ 0.91293339, -0.24630028])

***
To select everthing except 'sam', you can use `!=` or `~`

In [91]:
names != 'sam'

array([False,  True,  True,  True,  True, False,  True])

In [93]:
data[~(names == 'sam')]

array([[ 0.12364878,  0.688729  ,  0.54843   ,  1.29368215],
       [-0.22548625, -0.95891537, -1.37764871, -0.18546204],
       [-1.594141  , -0.13776815,  0.0409635 ,  0.74770632],
       [-0.75240311, -0.27632477,  0.81555435,  0.00660861],
       [-0.97706158,  0.07176566,  0.68049229, -0.19055745]])

In [119]:
mask = (names == 'sam') | (names=='bob') # for more than 1 cobdition. Use and (&), or or(|)
mask

array([ True,  True, False, False, False,  True, False])

In [120]:
data[mask]

array([[ 0.03012037,  0.89247625, -0.16728324,  0.91293339],
       [-0.33013837,  1.03685685, -0.76444672, -0.72360207],
       [ 1.27638825,  0.06818587, -0.44883013, -0.24630028]])

In [121]:
data[data<0]

array([-0.16728324, -0.33013837, -0.76444672, -0.72360207, -0.02855973,
       -0.47891146, -0.26946031, -0.11665027, -0.16274915, -0.45726756,
       -0.44883013, -0.24630028, -0.4951951 , -0.69942292])

### Array Reshaping
In machine learning and deep learning, you need to reshape data as per requirement of the model
#### Data Shape
`shape` attribute returns the tuple of the length of each dimension of the array

In [122]:
arr1 = np.array([11, 22, 33, 44, 55])
arr1.shape

(5,)

In [123]:
arr2d = np.array([[11, 22, 33],[44, 55, 66]])
arr2d.shape

(2, 3)

In [124]:
print('Row %d' %arr2d.shape[0])
print('Column %d' %arr2d.shape[1])

Row 2
Column 3


### Reshape Array from 1D to 2D
`reshape` - to reshape the array<br>
takes single arguement to specify new shape<br>
if you want to reshape 1d array to 2d array with 1 column, you can use `arr1.shape[0]` for first and 1 for second dimension

In [108]:
arr1 = np.array([11, 22, 33, 44, 55])
print(arr1)
print(arr1.shape)

[11 22 33 44 55]
(5,)


In [109]:
print(arr1.reshape((arr1.shape[0],1)))
print(arr1.reshape((arr1.shape[0],1)).shape)

[[11]
 [22]
 [33]
 [44]
 [55]]
(5, 1)


In [111]:
arr2 = np.array([1, 2, 3, 4, 5, 6])
arr2.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

### From 2D to 3D

In [112]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
print(arr1.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [113]:
arr1 = arr1.reshape(arr1.shape[0], arr1.shape[1],1)
print(arr1)
print(arr1.shape)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
(3, 3, 1)


## Array Broadcasting
### Array Arithmetic Limitations
Array with different shape and size cannot be added or subtracted in Arithmetic<br>
A one dimensional array with length 8 can be added or subtracted from another array of length 8 only<br>
This limittion in arithmetic is limiting<br>
Python has buildin functionlity **broadcasting** to address this

### Broadcasting

Broadcasting solves the problems of different shapes by replicating the smaller array along the last mismatched dimension

In [125]:
a = np.array([1, 2, 3])
print(a)
b = 2
print(b)
c = a + b
print(c)

[1 2 3]
2
[3 4 5]


### 2D array and Scalar

In [126]:
a = np.array([[1, 2, 3],[4, 5, 6]])
print(a)
b = 4
print(b)
c = a + b # scalar b will duplicate itself 5 more times to broadcast
print(c)

[[1 2 3]
 [4 5 6]]
4
[[ 5  6  7]
 [ 8  9 10]]


### 1D and 2D Array Broadcasting

In [127]:
a = np.array([[1, 2, 3],[4, 5, 6]])
print(a)
b = np.array([7, 8, 9])
print(b)
c = a+b  # 1D array b is broadcast across each row of 2D by creating a copy of itself
print(c)

[[1 2 3]
 [4 5 6]]
[7 8 9]
[[ 8 10 12]
 [11 13 15]]


### Limitation of Broadcasting

Broadcasting can be performed when<br>
1. the shape of each dimension in the array are equal<br>
or
2. one has dimension size 1

In [128]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print('a')
print(a)
print(a.shape)
b = np.array([6,7])
print('b')
print(b)
print(b.shape)
c = a+b #attempt to broadcast
print(c)

a
[[1 2 3]
 [4 5 6]]
(2, 3)
b
[6 7]
(2,)


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 